apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "flask-app.fullname" . }}-np
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "flask-app.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "flask-app.name" . }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
