apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.create }}
          {{ default (include "flask-app.fullname" .) .Values.serviceAccount.name | trunc 63 | trimSuffix "-" }}
        {{ else }}
          {{ .Values.serviceAccount.name }}
        {{ end }}
